_BASE_: "Base_Single_Stage.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 8
  BASE_LR: 0.005 
  STEPS: (22000, 30250)       
  MAX_ITER: 33000            
  WARMUP_ITERS: 1031
TEST:
  EVAL_PERIOD: 3300
VIS_PERIOD: 1000
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val')
  TEST: ('SUNRGBD_test',) 
  
  CATEGORY_NAMES: ('stationery', 'sink', 'table', 'floor mat', 'bottle', 'bookcase', 'bin', 'blinds', 'pillow', 'bicycle', 'refrigerator', 'night stand', 'chair', 'sofa', 'books', 'oven', 'towel', 'cabinet', 'window', 'curtain', 'bathtub', 'laptop', 'desk', 'television', 'clothes', 'stove', 'cup', 'shelves', 'box', 'shoes', 'mirror', 'door', 'picture', 'lamp', 'machine', 'counter', 'bed', 'toilet')
MODEL:
  DENSE_HEAD:
    NUM_CLASSES: 38